"""Add scenarios table

Revision ID: 472098a6ab59
Revises: 24b5f3912745
Create Date: 2025-11-07 20:39:12.662532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472098a6ab59'
down_revision: Union[str, Sequence[str], None] = '24b5f3912745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Таблицы edges и nodes уже существуют - пропускаем их создание
    
    # Используем прямой SQL с IF NOT EXISTS для SQLite
    from alembic import context
    conn = context.get_bind()
    
    # Создаем scenarios если не существует
    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS scenarios (
            id INTEGER NOT NULL PRIMARY KEY,
            user_id INTEGER NOT NULL,
            bot_id INTEGER,
            name VARCHAR(255) NOT NULL,
            description TEXT,
            icon VARCHAR(50),
            category VARCHAR(50),
            is_main BOOLEAN,
            is_library BOOLEAN,
            is_standard BOOLEAN,
            is_public BOOLEAN,
            content JSON,
            "order" INTEGER,
            created_at DATETIME,
            updated_at DATETIME,
            FOREIGN KEY(bot_id) REFERENCES bots (id) ON DELETE CASCADE,
            FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
        )
    """))
    
    # Создаем индексы если не существуют
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_scenarios_id ON scenarios (id)"))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_scenarios_bot_id ON scenarios (bot_id)"))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_scenarios_user_id ON scenarios (user_id)"))
    
    # Создаем scenario_versions если не существует
    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS scenario_versions (
            id INTEGER NOT NULL PRIMARY KEY,
            scenario_id INTEGER NOT NULL,
            content JSON,
            created_at DATETIME,
            FOREIGN KEY(scenario_id) REFERENCES scenarios (id) ON DELETE CASCADE
        )
    """))
    
    # Создаем индексы для scenario_versions
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_scenario_versions_id ON scenario_versions (id)"))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_scenario_versions_scenario_id ON scenario_versions (scenario_id)"))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite не поддерживает ALTER COLUMN
    # op.alter_column('users', 'hashed_password', existing_type=sa.VARCHAR(), nullable=False)
    op.drop_index(op.f('ix_scenario_versions_scenario_id'), table_name='scenario_versions')
    op.drop_index(op.f('ix_scenario_versions_id'), table_name='scenario_versions')
    op.drop_table('scenario_versions')
    op.drop_index(op.f('ix_scenarios_user_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_bot_id'), table_name='scenarios')
    op.drop_table('scenarios')
    # Таблицы edges и nodes не удаляем - они уже существовали
    # ### end Alembic commands ###
