"""Add provider-neutral AI invocation accounting and credit reservations."""
from alembic import op
import sqlalchemy as sa

revision = "ai_provider_layer_042"
down_revision = "legacy_plan_codes_to_current_041"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table("ai_provider_configs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(64), nullable=False), sa.Column("display_name", sa.String(128), nullable=False), sa.Column("adapter_code", sa.String(64), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("status", sa.String(32), nullable=False, server_default="unknown"), sa.Column("routing_priority", sa.Integer(), nullable=False, server_default="100"), sa.Column("secret_ref", sa.String(255)), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("code", name="uq_ai_provider_config_code"))
    op.create_table("ai_model_catalog", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("provider_id", sa.Integer(), sa.ForeignKey("ai_provider_configs.id", ondelete="RESTRICT"), nullable=False), sa.Column("model_code", sa.String(128), nullable=False), sa.Column("display_name", sa.String(128), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("deprecated", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("capabilities", sa.JSON(), nullable=False), sa.Column("structured_output_supported", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("max_context_units", sa.Integer()), sa.Column("max_output_units", sa.Integer()), sa.Column("feature_allow_list", sa.JSON()), sa.Column("routing_priority", sa.Integer(), nullable=False, server_default="100"), sa.Column("pricing_version", sa.String(64), nullable=False), sa.Column("pricing_rule", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("updated_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("provider_id", "model_code", name="uq_ai_model_provider_code"))
    op.create_index("ix_ai_model_route", "ai_model_catalog", ["enabled", "deprecated", "routing_priority"])
    op.create_table("ai_invocations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("bot_id", sa.Integer(), sa.ForeignKey("bots.id", ondelete="SET NULL")), sa.Column("feature", sa.String(96), nullable=False), sa.Column("capability", sa.String(64), nullable=False), sa.Column("provider_code", sa.String(64)), sa.Column("model_code", sa.String(128)), sa.Column("idempotency_key", sa.String(191), nullable=False), sa.Column("request_fingerprint", sa.String(64), nullable=False), sa.Column("provider_request_id", sa.String(191)), sa.Column("status", sa.String(32), nullable=False), sa.Column("input_units", sa.JSON(), nullable=False), sa.Column("output_units", sa.JSON(), nullable=False), sa.Column("provider_cost", sa.Numeric(18, 8)), sa.Column("provider_currency", sa.String(12)), sa.Column("ai_credits_charged", sa.Integer(), nullable=False, server_default="0"), sa.Column("pricing_version", sa.String(64)), sa.Column("started_at", sa.DateTime(), nullable=False), sa.Column("completed_at", sa.DateTime()), sa.Column("latency_ms", sa.Integer()), sa.Column("error_code", sa.String(64)), sa.Column("metadata", sa.JSON()), sa.UniqueConstraint("user_id", "idempotency_key", name="uq_ai_invocation_user_idempotency"))
    op.create_index("ix_ai_invocation_status_created", "ai_invocations", ["status", "started_at"]); op.create_index("ix_ai_invocation_provider_model", "ai_invocations", ["provider_code", "model_code"])
    op.create_table("ai_credit_reservations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("invocation_id", sa.Integer(), sa.ForeignKey("ai_invocations.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("reserved_amount", sa.Integer(), nullable=False), sa.Column("settled_amount", sa.Integer(), nullable=False, server_default="0"), sa.Column("released_amount", sa.Integer(), nullable=False, server_default="0"), sa.Column("status", sa.String(32), nullable=False), sa.Column("expires_at", sa.DateTime()), sa.Column("settled_at", sa.DateTime()), sa.Column("debit_ledger_entry_id", sa.Integer(), sa.ForeignKey("ai_credit_ledger_entries.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("invocation_id", name="uq_ai_credit_reservation_invocation"))
    op.create_index("ix_ai_credit_reservation_user_status", "ai_credit_reservations", ["user_id", "status"])


def downgrade():
    op.drop_table("ai_credit_reservations"); op.drop_table("ai_invocations"); op.drop_table("ai_model_catalog"); op.drop_table("ai_provider_configs")
